/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package de.virtimo

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class JiraReportPlugin implements Plugin<Project> {
    void apply(Project project) {

    }
}
