/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package de.virtimo

import de.virtimo.task.JiraReport
import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'de.virtimo.jira-report' plugin.
 */
class JiraReportPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("de.virtimo.jira-report")
        project.tasks.register("JiraReport", JiraReport.class)

        then:
        project.tasks.findByName("JiraReport") != null
    }
}
